# Generated by Django 4.1.4 on 2023-01-13 08:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Reference')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('type', models.CharField(choices=[('DEP', 'Deposit')], default='DEP', max_length=3, verbose_name='Type')),
                ('status', models.CharField(choices=[('SUC', 'Success'), ('PEN', 'Pending'), ('FAL', 'Failed')], default='PEN', max_length=3, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keep', models.BooleanField(default=False, verbose_name='Keep')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('last_four', models.CharField(max_length=4, verbose_name='Last Four')),
                ('exp_month', models.CharField(max_length=2, verbose_name='Expiration Month')),
                ('exp_year', models.CharField(max_length=4, verbose_name='Expiration Year')),
                ('authorization_code', models.CharField(max_length=255, verbose_name='Authorization Code')),
                ('signature', models.CharField(max_length=255, verbose_name='Signature')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Paystack data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
