# Generated by Django 4.1.4 on 2022-12-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAuthenticationProxyModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authtoken.token',),
        ),
    ]
