# Generated by Django 4.1.4 on 2023-01-28 00:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_seller_profile_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='earnings',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=10, verbose_name='Earnings'),
        ),
    ]
