# Generated by Django 4.1.4 on 2023-01-28 00:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_seller_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pending_earnings',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=10, verbose_name='Pending Earnings'),
        ),
    ]
