# Generated by Django 4.1.4 on 2023-02-05 20:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_seller_pending_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='earnings',
            field=models.DecimalField(decimal_places=19, default=Decimal('0'), max_digits=28, verbose_name='Earnings'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pending_earnings',
            field=models.DecimalField(decimal_places=19, default=Decimal('0'), max_digits=28, verbose_name='Pending Earnings'),
        ),
    ]
