# Generated by Django 4.1.4 on 2023-01-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='type',
            field=models.CharField(choices=[('DEP', 'Deposit'), ('WIT', 'Withdrawal')], default='DEP', max_length=3, verbose_name='Type'),
        ),
    ]
