# Generated by Django 4.1.4 on 2023-01-29 11:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_walletmodel_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='balance',
            field=models.DecimalField(decimal_places=19, default=Decimal('0'), max_digits=28),
        ),
    ]
