# Generated by Django 4.1.4 on 2023-01-24 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dalle2PromptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.URLField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('template', models.TextField()),
                ('template_params', models.JSONField()),
                ('model_options', models.JSONField()),
                ('examples', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_prompts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Image Prompt',
                'verbose_name_plural': 'Image Prompts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GPT3PromptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.URLField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('template', models.TextField()),
                ('template_params', models.JSONField()),
                ('model_options', models.JSONField()),
                ('examples', models.JSONField()),
                ('model', models.CharField(choices=[('text-davinci-003', 'Davinci'), ('text-curie-001', 'Curie'), ('text-babbage-001', 'Babbage'), ('text-ada-001', 'Ada')], max_length=255)),
                ('max_tokens', models.IntegerField(default=2048)),
                ('top_p', models.FloatField(default=1.0)),
                ('temparature', models.FloatField(default=0.9)),
                ('frequency_penalty', models.FloatField(default=0.0)),
                ('presence_penalty', models.FloatField(default=0.0)),
                ('suffix', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_prompts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Language Prompt',
                'verbose_name_plural': 'Language Prompts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GPT3PromptOutputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=255)),
                ('model_input', models.TextField()),
                ('input', models.JSONField(blank=True, null=True)),
                ('output', models.TextField()),
                ('model_snapshot', models.JSONField()),
                ('cost', models.FloatField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='language_prompt_outputs', to='jarvis.gpt3promptmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_prompt_outputs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Text Output',
                'verbose_name_plural': 'Text Outputs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Dalle2PromptOutputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=255)),
                ('model_input', models.TextField()),
                ('input', models.JSONField(blank=True, null=True)),
                ('output', models.TextField()),
                ('model_snapshot', models.JSONField()),
                ('cost', models.FloatField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_prompt_outputs', to='jarvis.dalle2promptmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_prompt_outputs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Image Output',
                'verbose_name_plural': 'Image Outputs',
                'ordering': ('-created_at',),
            },
        ),
    ]
