# Generated by Django 4.1.4 on 2023-01-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpt3promptmodel',
            name='examples',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpt3promptmodel',
            name='model',
            field=models.CharField(choices=[('text-davinci-003', 'Davinci'), ('text-curie-001', 'Curie'), ('text-babbage-001', 'Babbage'), ('text-ada-001', 'Ada')], default='text-davinci-003', max_length=255),
        ),
    ]
