# Generated by Django 4.1.4 on 2023-01-24 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0002_alter_gpt3promptmodel_examples_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dalle2promptmodel',
            name='model_options',
        ),
        migrations.RemoveField(
            model_name='gpt3promptmodel',
            name='model_options',
        ),
    ]
