# Generated by Django 4.1.4 on 2023-01-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0003_remove_dalle2promptmodel_model_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dalle2promptmodel',
            name='examples',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
