# Generated by Django 4.1.4 on 2023-01-25 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jarvis', '0004_alter_dalle2promptmodel_examples'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dalle2promptmodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Dalle2 Prompt', 'verbose_name_plural': 'Dalle2 Prompts'},
        ),
        migrations.AlterModelOptions(
            name='dalle2promptoutputmodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Dalle2 Output', 'verbose_name_plural': 'Dalle2 Outputs'},
        ),
        migrations.AlterModelOptions(
            name='gpt3promptmodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'GPT3 Prompt', 'verbose_name_plural': 'GPT3 Prompts'},
        ),
        migrations.AlterModelOptions(
            name='gpt3promptoutputmodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'GPT3 Output', 'verbose_name_plural': 'GPT3 Outputs'},
        ),
        migrations.RemoveField(
            model_name='dalle2promptoutputmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='gpt3promptoutputmodel',
            name='type',
        ),
        migrations.AlterField(
            model_name='dalle2promptmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dalle2_prompts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='dalle2promptoutputmodel',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dalle2_prompt_outputs', to='jarvis.dalle2promptmodel'),
        ),
        migrations.AlterField(
            model_name='dalle2promptoutputmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dalle2_prompt_outputs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='gpt3promptoutputmodel',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gpt3_prompt_outputs', to='jarvis.gpt3promptmodel'),
        ),
        migrations.AlterField(
            model_name='gpt3promptoutputmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpt3_prompt_outputs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
