# Generated by Django 4.1.4 on 2023-01-29 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jarvis', '0006_alter_dalle2promptmodel_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptOutputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('input', models.JSONField(blank=True, null=True)),
                ('output', models.TextField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=255)),
                ('cost', models.FloatField()),
                ('model_name', models.CharField(choices=[('gpt3', 'GPT3'), ('dalle2', 'DALLE2')], max_length=255)),
                ('model_input', models.TextField()),
                ('model_snapshot', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prompt_outputs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Output',
                'verbose_name_plural': 'Prompt Outputs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='gpt3promptoutputmodel',
            name='model',
        ),
        migrations.RemoveField(
            model_name='gpt3promptoutputmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='dalle2promptmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gpt3promptmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Dalle2PromptOutputModel',
        ),
        migrations.DeleteModel(
            name='GPT3PromptOutputModel',
        ),
    ]
