# Generated by Django 4.1.4 on 2023-01-29 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jarvis', '0007_promptoutputmodel_remove_gpt3promptoutputmodel_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptoutputmodel',
            name='model_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prompt_outputs_seller_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
