name: Trigger auto deployment for klerly-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/klerly-backend-AutoDeployTrigger-a07b00da-22fc-43fc-8ffc-b11177c525fe.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.KLERLYBACKEND_REGISTRY_USERNAME }}
          password: ${{ secrets.KLERLYBACKEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ojetokun/klerly-backend:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: ls .
